server:
  port: 8080
spring:
  application:
    name: "crypto-bot"
  devtools:
    add-properties: false

  profiles:
    include: null
  datasource:
    url: "/s"
    username: "/s"
    password: "/s"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQL5InnoDBDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
